# Generated by Django 3.2.20 on 2023-10-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='website',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
