name: Deploy to AWS
description: Deploys an application to AWS
inputs:
  app-name:
    default: artitone
    description: The name of the application to deploy
    required: true
  platform:
    default: python-3.7
    description: The platform to deploy the app onto
    required: false
  region:
    default: us-east-1
    description: The AWS region to deploy to
    required: false
runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::141376400952:role/Github-eb-deploy
        aws-region: ${{ inputs.region }}
    - name: Get Timestamp for Versioning
      shell: bash
      id: timestamp
      run: echo "TIMESTAMP=$(TZ="America/New_York" date +'%Y-%m-%d_%H:%M')" >> $GITHUB_OUTPUT
    - name: Install AWS EB CLI
      shell: bash
      run: pip install awsebcli
    - name: Deploy to Elastic Beanstalk
      shell: bash
      working-directory: artitone
      run: |
        eb init ${{ inputs.app-name }} --region ${{ inputs.region }} --platform ${{ inputs.platform }}
        eb deploy ${{ inputs.app-name }}-${{ github.ref_name }}-v2 --label ${{ inputs.app-name}}_${{ github.ref_name }}_${{ steps.timestamp.outputs.TIMESTAMP }}
        