# Generated by Django 3.2.20 on 2023-09-28 03:49

import artworks.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Include keywords that buyers would use to search for your item.', max_length=200)),
                ('price', models.FloatField(default=0)),
                ('texture', models.CharField(choices=[('SA', 'Satin'), ('MA', 'Matte'), ('RO', 'Rough')], max_length=2, null=True)),
                ('content', models.TextField(default='', help_text='Caption your artwork')),
                ('pubdate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=artworks.models._post_picture_path, validators=[artworks.models.file_size])),
            ],
        ),
        migrations.CreateModel(
            name='TaggedCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artworks.artwork')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks_taggedcustom_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artworks.artwork')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks_taggedcolors_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustrialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.FileField(blank=True, help_text='Upload your 3d model files for better exposure chances.', upload_to=artworks.models._post_3d_model_path, validators=[artworks.models.validate_3d_model_extension])),
                ('texture', models.ImageField(blank=True, help_text='Upload your 3d model texture as well.', upload_to=artworks.models._post_3d_model_path, validators=[artworks.models.file_size])),
                ('artwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='artworks.artwork')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='artworks.category')),
            ],
        ),
    ]
