# Generated by Django 4.2.4 on 2023-08-29 23:18

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artworks", "0001_initial"),
        ("profiles", "0001_initial"),
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.artist"
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="artworks.category",
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="colors",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="artworks.TaggedColors",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="pictures",
            field=models.ManyToManyField(
                blank=True, related_name="pictures", to="artworks.picture"
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="artworks.TaggedCustom",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
