# Generated by Django 3.2.20 on 2023-09-28 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrialmodel',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='artworks.artwork'),
        ),
    ]
