# Generated by Django 4.2.4 on 2023-09-05 05:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0003_artwork_pubdate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artwork",
            old_name="name",
            new_name="title",
        ),
    ]
