# Generated by Django 3.2.20 on 2023-09-28 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_alter_industrialmodel_artwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrialmodel',
            name='artwork',
        ),
        migrations.AddField(
            model_name='artwork',
            name='model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artworks.industrialmodel'),
        ),
    ]
