# Generated by Django 4.2.4 on 2023-09-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0004_rename_name_artwork_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="pictures",
            field=models.ManyToManyField(
                blank=True,
                help_text="Requirement:\n 1 on white background.",
                related_name="pictures",
                to="artworks.picture",
            ),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="title",
            field=models.CharField(
                help_text="Include keywords that buyers would use to search for your item.",
                max_length=200,
            ),
        ),
    ]
