# Generated by Django 3.2.8 on 2023-09-19 19:15

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('artworks', '0005_alter_artwork_pictures_alter_artwork_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='colors',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='colors', through='artworks.TaggedColors', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='tags', through='artworks.TaggedCustom', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
